services:
  mongodb_container:
    image: mongo:latest
    container_name: arc_e_tect_phonebook_db
    ports:
      - 37017:27017
    volumes:
      - arc_e_tect_phonebook_db_data_container:/data/db

volumes:
  arc_e_tect_phonebook_db_data_container: