/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.arc_e_tect.blog.phonebook;

import com.arc_e_tect.blog.phonebook.model.Contact;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class PhonebookApplicationTest {
    @Test
    void addContactToPhonebookTest() {
        PhonebookApplication classUnderTest = new PhonebookApplication();
        String searchKey = "searchKey";
        Contact contact = new Contact("+1 555 3247843");
        classUnderTest.addContactToPhonebook(searchKey, contact);
        assertTrue(classUnderTest.getPhonebook().containsKey(searchKey));
        assertEquals(contact, classUnderTest.getPhonebook().get(searchKey));
    }

    @Test
    void getPhoneNumberContactFromPhonebookTest() {
        PhonebookApplication classUnderTest = new PhonebookApplication();
        String searchKey = "searchKey";
        Contact contact = new Contact("+1 555 3247843");
        classUnderTest.addContactToPhonebook(searchKey, contact);
        assertEquals(contact.getPhoneNumber(),classUnderTest.getPhoneNumberContactFromPhonebook(searchKey));
    }
}