/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.arc_e_tect.blog.phonebook;

public class App {
    public String getGreeting() {
        return "Hello Arc-E-Tect.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
