/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.arc_e_tect.blog.phonebook;

import com.arc_e_tect.blog.phonebook.model.Contact;

import java.util.Hashtable;

public class PhonebookApplication {
    public static void main(String[] args) {
    }

    private Hashtable<String, Contact> phonebook = new Hashtable<>();
    Hashtable<String, Contact> getPhonebook() {
        return phonebook;
    }

    public void addContactToPhonebook(String searchString, Contact contact) {
        phonebook.put(searchString, contact);
    }

    public String getPhoneNumberContactFromPhonebook(String searchString) {
        return phonebook.get(searchString).getPhoneNumber();
    }
}
