name: Build of Master

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.github/badges/**'
      - '.idea/**'
      - '**/*.md'
      - '.github/workflows/merge**'
      - '.github/workflows/push**'
      - '.github/workflows/nigthly**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_ECR_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Prepare Gradle
        run: |
          ./gradlew clean

      - name: Check dependencies for vulnerabilities
        run: |
          echo "GitHubPackages.user=${{ secrets.REPO_GHA_USERNAME }}" > ~/.gradle/gradle.properties
          echo "GitHubPackages.key=${{ secrets.REPO_GHA_PAT }}" >> ~/.gradle/gradle.properties
          ./gradlew dependencyCheckAnalyze

      - name: Build with Gradle
        run: |
          ./gradlew build generateCucumberReports testReport bootJar

      - name: Update release with basic commit message
        if: env.GIT_COMMIT_MESSAGE_BODY == ''
        run: |
          ./gradlew releaseVersion --message="${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}"

      - name: Update release with extended commit message
        if: env.GIT_COMMIT_MESSAGE_BODY != ''
        run:  |
          ./gradlew releaseVersion --message="${{ env.GIT_COMMIT_MESSAGE_BODY }}"

      - name: Show version information
        run:  |
          ./gradlew printVersion

      - name: Push changes back to origin
        run: |
          git push origin --tags
          git push origin --all --force

      - name: Show version information
        run:  |
          ./gradlew printVersion

      - name: Upload bootJar
        uses: actions/upload-artifact@v2
        with:
          name: CPModel-Microservice
          path: build/libs

      - name: Upload Documentation
        uses: actions/upload-artifact@v2
        with:
          name: API-documentation
          path: build/docs

      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: build/reports/tests

      - name: Generate Jacoco Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v1.0.0
        with:
          jacoco-csv-file: build/reports/jacoco/jacoco.csv

      - name: Commit JaCoCo badge
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply CI initiated changes
          file_pattern: .github/badges/*

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"

      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: build/reports/jacoco

  push-to-ECR:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_ECR_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download bootJar
        uses: actions/download-artifact@v2
        with:
          name: CPModel-Microservice
          path: build/libs

      - name: Build Docker image
        run: |
          ./gradlew docker

      - name: Push Docker image
        run: |
          ./gradlew dockerTagsPush

