name: Build of Master

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.github/badges/**'
      - '.idea/**'
      - '**/*.md'
      - '.github/workflows/nigthly**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Prepare Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean

      #      - name: Check dependencies for vulnerabilities
      #        run: |
      #          ./gradlew dependencyCheckAnalyze

      - name: Build with Gradle
        run: |
          ./gradlew build asciidoctor openapi3 postman

      - name: Push changes back to origin
        run: |
          git push origin --tags
          git push origin --all --force

      - name: Show version information
        run:  |
          ./gradlew printVersion

      - name: Upload bootJar
        uses: actions/upload-artifact@v2
        with:
          name: Arc-E-Tect_Phonebook-Microservice
          path: build/libs

      - name: Upload Documentation
        uses: actions/upload-artifact@v2
        with:
          name: API-documentation
          path: |
            build/docs
            build/api-spec

      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: build/reports/tests

      - name: Visualize Sources
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"

      - name: Generate Jacoco Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v1.0.0
        with:
          jacoco-csv-file: build/reports/jacoco/jacoco.csv

      - name: Commit JaCoCo badge
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply CI initiated changes
          file_pattern: .github/badges/*

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"

      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: build/reports/jacoco

