name: Check Merge Request Gradle

on:
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '.github/badges/**'
      - '.idea/**'
      - '**/*.md'
    types: [opened,reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Prepare Gradle
        run: |
          ./gradlew clean

      - name: Check dependencies for vulnerabilities
        run: |
          echo "GitHubPackages.user=${{ secrets.REPO_GHA_USERNAME }}" > ~/.gradle/gradle.properties
          echo "GitHubPackages.key=${{ secrets.REPO_GHA_PAT }}" >> ~/.gradle/gradle.properties
          ./gradlew dependencyCheckAnalyze

      - name: Build with Gradle
        run: |
          ./gradlew build -DuseDocker=true

