name: 'nightly artifacts cleanup'
on:
  schedule:
    - cron: '0 1 * * *' # every night at 1 am UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          expire-in: 7days # Set this to 0 to delete all artifacts