# Worfklow for https://jmfayard.github.io/refreshVersions/

name: RefreshVersions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1'

jobs:
  "Refresh-Versions":
    runs-on: "ubuntu-latest"
    steps:
      - id: step-0
        name: check-out
        uses: actions/checkout@v4
        with:
          ref: master
      - id: step-1
        name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - id: step-2
        name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - id: step-3
        name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - id: step-4
        name: create-branch
        uses: peterjgrainger/action-create-branch@v3
        with:
          branch: refresh-versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: step-5
        name: gradle refreshVersions
        uses: gradle/gradle-build-action@v3
        with:
          arguments: refreshVersions
      - id: step-6
        name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: noreply@github.com
          message: Refresh versions.properties
          new_branch: refresh-versions
          push: --force --set-upstream origin refresh-versions
      - id: step-7
        name: Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: refresh-versions
          destination_branch: master
          pr_title: Upgrade gradle dependencies
          pr_body: '[refreshVersions](https://github.com/jmfayard/refreshVersions) has found those library updates!'
          pr_draft: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
