name: Visualize Source Code

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.github/**'
      - '.idea/**'

jobs:
  visualize:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Visualize Sources
        uses: githubocto/repo-visualizer@0.8.1
        with:
          root_path: "src/"
          max_depth: 10

